In [59]:
 import numpy as np


In [4]:
arr = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [6]:
numpy.array(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [9]:
arr2=numpy.array(arr)

In [10]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
arr2d=arr2.reshape(4,4)

In [36]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
arr2d[0:2,3:4]

array([[4],
       [8]])

In [14]:
arr2d[2:4,0:2]

array([[ 9, 10],
       [13, 14]])

In [15]:
arr2d[1,1]

6

In [16]:
arr2d[0,0:2,2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [21]:
arr2d[0,0]:[2,2]

In [31]:
arr2d[[0,0],[2,]]

array([3, 3])

In [37]:
arr2d[[1,0],[2,0]]

array([7, 1])

In [41]:
arr = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [43]:
arr2=numpy.array(arr)

In [46]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
arr2d[[1,0],[2,0]]

array([7, 1])

In [47]:
 arr2d[1]

array([5, 6, 7, 8])

In [48]:
arr2d[1,2]

7

In [54]:
arr2d[0:2,0:1]

array([[1],
       [5]])

In [57]:
arr2d[[2,1],[1,3]]

array([10,  8])

In [63]:
np.ones(2)

array([1., 1.])

In [65]:
np.ones(10)*3

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])